connect:
  host: "172.0.0.1"
  port: 6379
  db: 10
  
# Default
language:
  id: en
  text: English
package:
  id: be
  text: Backend
  
account: 
  - 
    username: "username"
    password: "password"
  - 
    username: "express_translate"
    password: "password"

